name: Bump version and auto-release (python and docker)
on:
  push:
    branches:
      - main


jobs:
  bump-version-python-docker-release:
    uses: openclimatefix/.github/.github/workflows/python-docker-release.yml@docker-release
    secrets:
      token: ${{ secrets.PYPI_API_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
